title: Guillaume Dua - Publications
tagline: A blog about C++, conference trip reports and publications
description: Personal publications

url: https://guillaumedua.github.io/publications
baseurl: /publications

remote_theme: hydecorp/hydejack@v9.2.1

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

hydejack:
  no_inline_css: true

styles:
  - /publications/assets/css/custom.css

markdown: kramdown
